import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui-components/sidebar";
import Footer from "@/components/ui-components/footer";
import { DrawerProvider } from "@/contextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home DTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#F4F6F9' }} className={inter.className}>
        <DrawerProvider>
        <Sidebar />
        {children}
        <Footer />
        </DrawerProvider>
      </body>
    </html>
  );
}
