import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { DrawerProvider } from "@/contextApi";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";
import AppBar from "@/components/appbar";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home DTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#F4F6F9' }} className={inter.className}>
        <DrawerProvider>
          <div className="flex">
            <Sidebar />
            <AppBar />
            <div className="w-full mt-14 p-4">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
          </div>
          {/* <Footer /> */}
        </DrawerProvider>
      </body>
    </html>
  );
}
